spring:
  application:
    name: labiii

  datasource:
    driver-class-name: org.postgresql.Driver
    username: labiii
    password: labiii
    url: jdbc:postgresql://localhost:5432/db_schema
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update

server:
  port: 8080