spring:
  application:
    name: labiii

  datasource:
    driver-class-name: org.postgresql.Driver
    username: labiii
    password: labiii
    url: jdbc:postgresql://localhost:5432/labiii
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update

jwt:
  secret: secret
  expirationMs: 36000000

server:
  port: 8080